language: perl
perl:
  - "5.20"
  - "5.18"
  - "5.10"

before_install:
  - cpanm --quiet --notest --no-man-pages Test::Pod Test::Pod::Coverage Devel::LeakGuard::Object Test::WWW::Selenium::Catalyst Test::NoTabs Catalyst::Devel

install:
  - cpanm --quiet --notest --no-man-pages --installdeps .

notifications:
  email: false
